// Bundled site configs for terratheme-browser content script
// Auto-generated from extension/sites/*.json — keep both in sync
const TERRA_SITE_CONFIGS = [
  {
    "version": 2,
    "match": ["*://chatgpt.com/*"],
    "rules": [
      {
        "selector": ":root",
        "important": true,
        "set": {
          "--main-surface-background": "var(--tt-base)",
          "--main-surface-secondary": "var(--tt-low)",
          "--main-surface-tertiary": "var(--tt-high)",
          "--message-surface": "var(--tt-base)",
          "--sidebar-surface-primary": "var(--tt-base)",
          "--sidebar-surface-secondary": "var(--tt-low)",
          "--sidebar-surface-tertiary": "var(--tt-base)",
          "--text-primary": "var(--tt-standard)",
          "--text-secondary": "var(--tt-muted)",
          "--text-tertiary": "var(--tt-muted)",
          "--text-quaternary": "color-mix(in srgb, var(--tt-muted) 60%, transparent)",
          "--border-primary": "var(--tt-outline)",
          "--border-secondary": "var(--tt-outline-variant)",
          "--border-tertiary": "color-mix(in srgb, var(--tt-outline) 30%, transparent)",
          "--bg-primary": "var(--tt-c4)",
          "--bg-primary-hover": "color-mix(in srgb, var(--tt-c4) 88%, var(--tt-standard) 12%)",
          "--bg-primary-disabled": "color-mix(in srgb, var(--tt-c4) 45%, transparent)",
          "--text-primary-on-primary": "var(--tt-on-c4)",
          "--text-primary-on-primary-disabled": "color-mix(in srgb, var(--tt-on-c4) 55%, transparent)",
          "--text-primary-on-primary-hover": "var(--tt-on-c4)",
          "--bg-danger": "var(--tt-error)",
          "--text-danger": "var(--tt-error)",
          "--text-danger-on-danger": "var(--tt-on-error)",
          "--bg-success": "var(--tt-c2)",
          "--text-success": "var(--tt-c2)",
          "--text-success-on-success": "var(--tt-on-c2)",
          "--bg-warning": "var(--tt-c1)",
          "--text-warning": "var(--tt-c1)",
          "--bg-contrast": "var(--tt-inverse-base)",
          "--text-contrast": "var(--tt-inverse-standard)",
          "--search-background": "var(--tt-low)",
          "--search-border-color": "var(--tt-outline)",
          "--search-text-color": "var(--tt-standard)",
          "--overlay-background": "var(--tt-scrim)",
          "--popup-background": "var(--tt-high)",
          "--popup-border": "var(--tt-outline-variant)",
          "--code-background": "var(--tt-low)",
          "--selection-background": "color-mix(in srgb, var(--tt-c4) 30%, transparent)",
          "--component-background": "var(--tt-low)",
          "--component-border": "var(--tt-outline-variant)",
          "--focus-ring-color": "var(--tt-c4)",
          "--link-color": "var(--tt-c4)",
          "--link-hover-color": "color-mix(in srgb, var(--tt-c4) 85%, var(--tt-standard) 15%)",
          "--icon-color": "var(--tt-standard)",
          "--icon-secondary": "var(--tt-muted)",
          "--surface-primary": "var(--tt-base)",
          "--surface-secondary": "var(--tt-low)",
          "--surface-tertiary": "var(--tt-high)",
          "--canvas-background": "var(--tt-low)",
          "--thread-background": "var(--tt-base)"
        }
      },
      {
        "selector": ".bg-token-main-surface-primary",
        "important": false,
        "set": { "background-color": "var(--tt-base)" }
      },
      {
        "selector": ".bg-token-main-surface-secondary",
        "important": false,
        "set": { "background-color": "var(--tt-low)" }
      },
      {
        "selector": ".bg-token-main-surface-tertiary",
        "important": false,
        "set": { "background-color": "var(--tt-high)" }
      },
      {
        "selector": ".bg-token-sidebar-surface-primary",
        "important": false,
        "set": { "background-color": "var(--tt-base)" }
      },
      {
        "selector": ".bg-token-sidebar-surface-secondary",
        "important": false,
        "set": { "background-color": "var(--tt-low)" }
      },
      {
        "selector": ".bg-token-sidebar-surface-tertiary",
        "important": false,
        "set": { "background-color": "var(--tt-base)" }
      },
      {
        "selector": ".text-token-text-primary",
        "important": false,
        "set": { "color": "var(--tt-standard)" }
      },
      {
        "selector": ".text-token-text-secondary",
        "important": false,
        "set": { "color": "var(--tt-muted)" }
      },
      {
        "selector": ".text-token-text-tertiary",
        "important": false,
        "set": { "color": "color-mix(in srgb, var(--tt-muted) 60%, transparent)" }
      },
      {
        "selector": ".border-token-border-primary",
        "important": false,
        "set": { "border-color": "var(--tt-outline)" }
      },
      {
        "selector": ".border-token-border-secondary",
        "important": false,
        "set": { "border-color": "var(--tt-outline-variant)" }
      }
    ]
  },
  {
    "version": 2,
    "match": ["*://github.com/*"],
    "rules": [
      {
        "selector": ":root",
        "important": true,
        "set": {
          "--bgColor-default": "var(--tt-base)",
          "--bgColor-muted": "var(--tt-low)",
          "--bgColor-inset": "var(--tt-low)",
          "--bgColor-emphasis": "var(--tt-low)",
          "--bgColor-disabled": "var(--tt-low)",
          "--bgColor-transparent": "transparent",
          "--fgColor-default": "var(--tt-standard)",
          "--fgColor-muted": "var(--tt-muted)",
          "--fgColor-neutral": "var(--tt-muted)",
          "--fgColor-disabled": "var(--tt-muted)",
          "--fgColor-onEmphasis": "var(--tt-standard)",
          "--borderColor-default": "var(--tt-outline)",
          "--borderColor-muted": "var(--tt-outline-variant)",
          "--borderColor-emphasis": "var(--tt-outline)",
          "--borderColor-disabled": "transparent",
          "--borderColor-translucent": "transparent",
          "--overlay-bgColor": "var(--tt-high)",
          "--tooltip-bgColor": "var(--tt-high)",
          "--selection-bgColor": "color-mix(in srgb, var(--tt-c4) 40%, transparent)",
          "--focus-outlineColor": "var(--tt-c4)",
          "--fgColor-accent": "var(--tt-c4)",
          "--fgColor-link": "var(--tt-c4)",
          "--bgColor-accent-emphasis": "color-mix(in srgb, var(--tt-c4) 72%, transparent)",
          "--bgColor-accent-muted": "color-mix(in srgb, var(--tt-c4) 12%, transparent)",
          "--borderColor-accent-emphasis": "var(--tt-c4)",
          "--borderColor-accent-muted": "color-mix(in srgb, var(--tt-c4) 40%, transparent)",
          "--fgColor-success": "var(--tt-c2)",
          "--bgColor-success-emphasis": "var(--tt-c2)",
          "--bgColor-success-muted": "color-mix(in srgb, var(--tt-c2) 18%, transparent)",
          "--borderColor-success-emphasis": "var(--tt-c2)",
          "--borderColor-success-muted": "color-mix(in srgb, var(--tt-c2) 45%, transparent)",
          "--fgColor-danger": "var(--tt-error)",
          "--bgColor-danger-emphasis": "var(--tt-error)",
          "--bgColor-danger-muted": "color-mix(in srgb, var(--tt-error) 18%, transparent)",
          "--borderColor-danger-emphasis": "var(--tt-error)",
          "--borderColor-danger-muted": "color-mix(in srgb, var(--tt-error) 45%, transparent)",
          "--fgColor-attention": "var(--tt-c1)",
          "--bgColor-attention-emphasis": "var(--tt-c1)",
          "--bgColor-attention-muted": "color-mix(in srgb, var(--tt-c1) 18%, transparent)",
          "--borderColor-attention-emphasis": "var(--tt-c1)",
          "--borderColor-attention-muted": "color-mix(in srgb, var(--tt-c1) 45%, transparent)",
          "--fgColor-severe": "var(--tt-c3)",
          "--bgColor-severe-emphasis": "var(--tt-c3)",
          "--bgColor-severe-muted": "color-mix(in srgb, var(--tt-c3) 18%, transparent)",
          "--borderColor-severe-emphasis": "var(--tt-c3)",
          "--borderColor-severe-muted": "color-mix(in srgb, var(--tt-c3) 45%, transparent)",
          "--fgColor-done": "var(--tt-c0)",
          "--bgColor-done-emphasis": "var(--tt-c0)",
          "--bgColor-done-muted": "color-mix(in srgb, var(--tt-c0) 18%, transparent)",
          "--borderColor-done-emphasis": "var(--tt-c0)",
          "--borderColor-done-muted": "color-mix(in srgb, var(--tt-c0) 45%, transparent)",
          "--fgColor-sponsors": "var(--tt-c3)",
          "--bgColor-sponsors-emphasis": "var(--tt-c3)",
          "--bgColor-sponsors-muted": "color-mix(in srgb, var(--tt-c3) 18%, transparent)",
          "--borderColor-sponsors-emphasis": "var(--tt-c3)",
          "--borderColor-sponsors-muted": "color-mix(in srgb, var(--tt-c3) 45%, transparent)",
          "--button-primary-bgColor-rest": "var(--tt-c4)",
          "--button-primary-bgColor-hover": "color-mix(in srgb, var(--tt-c4) 88%, var(--tt-standard) 12%)",
          "--button-primary-bgColor-active": "color-mix(in srgb, var(--tt-c4) 80%, var(--tt-standard) 20%)",
          "--button-primary-bgColor-disabled": "color-mix(in srgb, var(--tt-c4) 45%, transparent)",
          "--button-primary-fgColor-rest": "var(--tt-on-c4)",
          "--button-primary-fgColor-disabled": "color-mix(in srgb, var(--tt-on-c4) 55%, transparent)",
          "--button-primary-borderColor-rest": "color-mix(in srgb, var(--tt-c4) 70%, var(--tt-standard) 30%)",
          "--button-primary-borderColor-hover": "color-mix(in srgb, var(--tt-c4) 62%, var(--tt-standard) 38%)",
          "--button-primary-borderColor-active": "color-mix(in srgb, var(--tt-c4) 55%, var(--tt-standard) 45%)",
          "--button-primary-borderColor-disabled": "transparent",
          "--button-primary-shadow-selected": "0px 0px 0px 0px transparent",
          "--button-default-bgColor-rest": "var(--tt-low)",
          "--button-default-bgColor-hover": "var(--tt-base)",
          "--button-default-bgColor-active": "var(--tt-high)",
          "--button-default-bgColor-disabled": "var(--tt-low)",
          "--button-default-fgColor-rest": "var(--tt-standard)",
          "--button-default-borderColor-rest": "var(--tt-outline-variant)",
          "--button-default-borderColor-hover": "var(--tt-outline)",
          "--button-default-borderColor-active": "var(--tt-outline)",
          "--button-default-shadow-resting": "0px 0px 0px 0px transparent",
          "--button-outline-fgColor-rest": "var(--tt-c4)",
          "--button-outline-fgColor-hover": "var(--tt-c4)",
          "--button-outline-fgColor-disabled": "color-mix(in srgb, var(--tt-c4) 45%, transparent)",
          "--button-outline-fgColor-active": "var(--tt-on-c4)",
          "--button-outline-bgColor-rest": "transparent",
          "--button-outline-bgColor-hover": "color-mix(in srgb, var(--tt-c4) 12%, transparent)",
          "--button-outline-bgColor-active": "var(--tt-c4)",
          "--button-outline-shadow-selected": "0px 0px 0px 0px transparent",
          "--button-danger-fgColor-rest": "var(--tt-error)",
          "--button-danger-fgColor-hover": "var(--tt-on-error)",
          "--button-danger-fgColor-active": "var(--tt-on-error)",
          "--button-danger-fgColor-disabled": "color-mix(in srgb, var(--tt-error) 45%, transparent)",
          "--button-danger-bgColor-rest": "transparent",
          "--button-danger-bgColor-hover": "var(--tt-error)",
          "--button-danger-bgColor-active": "color-mix(in srgb, var(--tt-error) 85%, var(--tt-standard) 15%)",
          "--button-danger-bgColor-disabled": "transparent",
          "--button-danger-borderColor-rest": "color-mix(in srgb, var(--tt-error) 60%, transparent)",
          "--button-danger-borderColor-hover": "var(--tt-error)",
          "--button-danger-borderColor-active": "var(--tt-error)",
          "--button-danger-iconColor-rest": "var(--tt-error)",
          "--button-danger-iconColor-hover": "var(--tt-on-error)",
          "--button-danger-shadow-selected": "0px 0px 0px 0px transparent",
          "--button-inactive-bgColor": "transparent",
          "--button-inactive-fgColor": "var(--tt-muted)",
          "--button-invisible-bgColor-rest": "transparent",
          "--button-invisible-bgColor-hover": "color-mix(in srgb, var(--tt-standard) 8%, transparent)",
          "--button-invisible-bgColor-active": "color-mix(in srgb, var(--tt-standard) 12%, transparent)",
          "--button-invisible-bgColor-disabled": "transparent",
          "--button-invisible-iconColor-rest": "var(--tt-muted)",
          "--button-invisible-iconColor-hover": "var(--tt-standard)",
          "--button-invisible-iconColor-disabled": "color-mix(in srgb, var(--tt-muted) 45%, transparent)",
          "--button-invisible-fgColor-rest": "var(--tt-standard)",
          "--button-invisible-fgColor-hover": "var(--tt-standard)",
          "--button-invisible-fgColor-active": "var(--tt-standard)",
          "--button-invisible-fgColor-disabled": "color-mix(in srgb, var(--tt-standard) 45%, transparent)",
          "--button-invisible-borderColor-rest": "transparent",
          "--button-invisible-borderColor-hover": "transparent",
          "--button-invisible-borderColor-active": "transparent",
          "--button-invisible-borderColor-disabled": "transparent",
          "--control-bgColor-rest": "var(--tt-low)",
          "--control-bgColor-hover": "var(--tt-base)",
          "--control-bgColor-active": "var(--tt-high)",
          "--control-bgColor-disabled": "var(--tt-low)",
          "--control-bgColor-selected": "var(--tt-base)",
          "--control-fgColor-rest": "var(--tt-standard)",
          "--control-fgColor-placeholder": "var(--tt-muted)",
          "--control-fgColor-disabled": "color-mix(in srgb, var(--tt-standard) 45%, transparent)",
          "--control-iconColor-rest": "var(--tt-muted)",
          "--control-borderColor-rest": "var(--tt-outline-variant)",
          "--control-borderColor-emphasis": "var(--tt-outline)",
          "--control-borderColor-selected": "var(--tt-c4)",
          "--control-borderColor-disabled": "color-mix(in srgb, var(--tt-outline) 25%, transparent)",
          "--control-checked-bgColor-rest": "var(--tt-c4)",
          "--control-checked-bgColor-hover": "color-mix(in srgb, var(--tt-c4) 88%, var(--tt-standard) 12%)",
          "--control-checked-bgColor-active": "color-mix(in srgb, var(--tt-c4) 80%, var(--tt-standard) 20%)",
          "--control-checked-bgColor-disabled": "color-mix(in srgb, var(--tt-c4) 45%, transparent)",
          "--control-checked-fgColor-rest": "var(--tt-on-c4)",
          "--control-checked-fgColor-disabled": "color-mix(in srgb, var(--tt-on-c4) 55%, transparent)",
          "--control-checked-borderColor-rest": "var(--tt-c4)",
          "--control-checked-borderColor-hover": "var(--tt-c4)",
          "--control-checked-borderColor-active": "var(--tt-c4)",
          "--control-checked-borderColor-disabled": "transparent",
          "--controlTrack-bgColor-rest": "var(--tt-base)",
          "--controlTrack-bgColor-hover": "var(--tt-high)",
          "--controlTrack-bgColor-active": "var(--tt-high)",
          "--controlTrack-bgColor-disabled": "var(--tt-low)",
          "--controlTrack-borderColor-rest": "var(--tt-outline-variant)",
          "--controlTrack-borderColor-disabled": "color-mix(in srgb, var(--tt-outline) 25%, transparent)",
          "--controlTrack-fgColor-rest": "var(--tt-muted)",
          "--controlTrack-fgColor-disabled": "color-mix(in srgb, var(--tt-muted) 45%, transparent)"
        }
      }
    ]
  },
  {
    "version": 2,
    "match": ["*://monkeytype.com/*"],
    "rules": [
      {
        "selector": ":root",
        "important": true,
        "set": {
          "--bg-color": "var(--tt-base)",
          "--main-color": "var(--tt-c4)",
          "--caret-color": "var(--tt-c4)",
          "--sub-color": "var(--tt-muted)",
          "--sub-alt-color": "var(--tt-low)",
          "--text-color": "var(--tt-standard)",
          "--error-color": "var(--tt-error)",
          "--error-extra-color": "color-mix(in srgb, var(--tt-error) 70%, var(--tt-standard) 30%)",
          "--colorful-error-color": "var(--tt-error)",
          "--colorful-error-extra-color": "color-mix(in srgb, var(--tt-error) 70%, var(--tt-standard) 30%)",
          "--text-color-dark": "color-mix(in srgb, var(--tt-standard) 40%, var(--tt-base) 60%)"
        }
      },
      {
        "selector": "#words",
        "set": { "color": "var(--tt-standard)", "background-color": "transparent" }
      },
      {
        "selector": "#words .word letter.correct",
        "set": { "color": "var(--tt-standard)" }
      },
      {
        "selector": "#words .word letter.incorrect",
        "set": { "color": "var(--tt-error)" }
      },
      {
        "selector": "#words .word letter.extraLetter",
        "set": { "color": "var(--tt-error)" }
      },
      {
        "selector": "#words .word letter.missingLetter",
        "set": { "color": "color-mix(in srgb, var(--tt-error) 50%, transparent)" }
      },
      {
        "selector": ".key",
        "set": { "color": "var(--tt-muted)", "background-color": "var(--tt-low)" }
      },
      {
        "selector": ".key.correct",
        "set": {
          "color": "var(--tt-standard)",
          "background-color": "color-mix(in srgb, var(--tt-c4) 15%, var(--tt-low) 85%)"
        }
      },
      {
        "selector": ".key.incorrect",
        "set": { "color": "var(--tt-on-error)", "background-color": "var(--tt-error)" }
      }
    ]
  },
  {
    "version": 2,
    "match": ["*://www.reddit.com/*"],
    "rules": [
      {
        "selector": ":root",
        "important": true,
        "set": {
          "--color-ui-canvas": "var(--tt-base)",
          "--color-neutral-background": "var(--tt-base)",
          "--color-neutral-background-weak": "var(--tt-low)",
          "--color-neutral-background-medium": "var(--tt-low)",
          "--color-neutral-background-hover": "var(--tt-high)",
          "--color-neutral-background-selected": "var(--tt-low)",
          "--color-neutral-content": "var(--tt-standard)",
          "--color-neutral-content-weak": "var(--tt-muted)",
          "--color-neutral-content-strong": "var(--tt-standard)",
          "--color-neutral-content-disabled": "color-mix(in srgb, var(--tt-standard) 45%, transparent)",
          "--color-neutral-border": "var(--tt-outline)",
          "--color-neutral-border-weak": "color-mix(in srgb, var(--tt-outline) 50%, transparent)",
          "--color-neutral-border-medium": "var(--tt-outline)",
          "--color-neutral-border-strong": "var(--tt-outline)",
          "--color-primary": "var(--tt-c4)",
          "--color-primary-hover": "color-mix(in srgb, var(--tt-c4) 85%, var(--tt-standard) 15%)",
          "--color-primary-visited": "color-mix(in srgb, var(--tt-c4) 70%, var(--tt-c2) 30%)",
          "--color-primary-onBackground": "var(--tt-on-c4)",
          "--color-primary-onBackground-selected": "var(--tt-on-c4)",
          "--color-primary-background": "var(--tt-c4)",
          "--color-primary-background-hover": "color-mix(in srgb, var(--tt-c4) 85%, var(--tt-standard) 15%)",
          "--color-primary-background-selected": "color-mix(in srgb, var(--tt-c4) 70%, var(--tt-standard) 30%)",
          "--color-secondary": "var(--tt-c2)",
          "--color-secondary-background": "var(--tt-low)",
          "--color-secondary-background-hover": "var(--tt-base)",
          "--color-secondary-background-selected": "var(--tt-high)",
          "--color-secondary-plain": "var(--tt-standard)",
          "--color-secondary-plain-hover": "var(--tt-standard)",
          "--color-secondary-onBackground": "var(--tt-standard)",
          "--color-secondary-weak": "var(--tt-muted)",
          "--color-danger-content": "var(--tt-error)",
          "--color-danger-content-hover": "color-mix(in srgb, var(--tt-error) 80%, var(--tt-standard) 20%)",
          "--color-danger-content-default": "var(--tt-on-error)",
          "--color-danger-background": "var(--tt-error)",
          "--color-danger-background-hover": "color-mix(in srgb, var(--tt-error) 80%, var(--tt-standard) 20%)",
          "--color-danger-onBackground": "var(--tt-on-error)",
          "--color-danger-background-disabled": "color-mix(in srgb, var(--tt-error) 30%, transparent)",
          "--color-success-content": "var(--tt-c2)",
          "--color-success-background": "var(--tt-c2)",
          "--color-success-background-hover": "color-mix(in srgb, var(--tt-c2) 80%, var(--tt-standard) 20%)",
          "--color-success-onBackground": "var(--tt-on-c2)",
          "--color-success-background-disabled": "color-mix(in srgb, var(--tt-c2) 30%, transparent)",
          "--color-input-background": "var(--tt-low)",
          "--color-input-hover-background": "var(--tt-base)",
          "--color-input-border": "var(--tt-outline)",
          "--color-input-hover-border": "var(--tt-outline)",
          "--color-input-active-border": "var(--tt-c4)",
          "--color-input-filled-background": "var(--tt-low)",
          "--color-interactive-hover": "color-mix(in srgb, var(--tt-standard) 8%, transparent)",
          "--color-interactive-active": "color-mix(in srgb, var(--tt-standard) 12%, transparent)",
          "--color-interactive-pressed": "color-mix(in srgb, var(--tt-standard) 16%, transparent)",
          "--color-interactive-hover-inverted": "color-mix(in srgb, var(--tt-standard) 8%, transparent)",
          "--color-interactive-active-inverted": "color-mix(in srgb, var(--tt-standard) 12%, transparent)",
          "--color-interactive-pressed-inverted": "color-mix(in srgb, var(--tt-standard) 16%, transparent)",
          "--color-tone-1": "var(--tt-standard)",
          "--color-tone-2": "var(--tt-muted)",
          "--color-tone-3": "var(--tt-muted)",
          "--color-tone-4": "var(--tt-muted)",
          "--color-tone-5": "var(--tt-muted)",
          "--color-tone-6": "var(--tt-muted)",
          "--color-tone-7": "var(--tt-muted)"
        }
      },
      {
        "selector": "shreddit-app",
        "important": true,
        "set": { "background-color": "var(--tt-base)", "color": "var(--tt-standard)" }
      }
    ]
  },
  {
    "version": 2,
    "match": ["*://www.youtube.com/*", "*://youtube.com/*"],
    "rules": [
      {
        "selector": ":root",
        "important": true,
        "set": {
          "--yt-spec-base-background": "var(--tt-base)",
          "--yt-spec-raised-background": "var(--tt-high)",
          "--yt-spec-additive-background": "color-mix(in srgb, var(--tt-standard) 5%, transparent)",
          "--yt-spec-additive-background-inverse": "color-mix(in srgb, var(--tt-base) 5%, transparent)",
          "--yt-spec-solid-background": "var(--tt-standard)",
          "--yt-spec-solid-background-inverse": "var(--tt-low)",
          "--yt-spec-text-primary": "var(--tt-standard)",
          "--yt-spec-text-secondary": "var(--tt-muted)",
          "--yt-spec-text-disabled": "color-mix(in srgb, var(--tt-standard) 50%, transparent)",
          "--yt-spec-text-primary-inverse": "var(--tt-base)",
          "--yt-spec-text-secondary-inverse": "color-mix(in srgb, var(--tt-base) 70%, var(--tt-standard) 30%)",
          "--yt-spec-outline": "var(--tt-outline)",
          "--yt-spec-outline-opaque": "var(--tt-outline)",
          "--yt-spec-outline-rim": "color-mix(in srgb, var(--tt-outline) 30%, transparent)",
          "--yt-spec-outline-inverse": "color-mix(in srgb, var(--tt-outline) 50%, var(--tt-base) 50%)",
          "--yt-spec-outline-rim-inverse": "color-mix(in srgb, var(--tt-outline) 15%, transparent)",
          "--yt-spec-outline-opaque-inverse": "color-mix(in srgb, var(--tt-outline) 40%, var(--tt-base) 60%)",
          "--yt-spec-link-icon-color": "var(--tt-c4)",
          "--yt-spec-wordmark-text": "var(--tt-standard)",
          "--yt-spec-call-to-action": "var(--tt-c4)",
          "--yt-spec-brand-button-background": "var(--tt-c4)",
          "--yt-spec-brand-button-text": "var(--tt-on-c4)",
          "--yt-spec-brand-link-text": "var(--tt-c4)",
          "--yt-spec-error-background": "color-mix(in srgb, var(--tt-error) 20%, transparent)",
          "--yt-spec-text-warning": "var(--tt-c1)",
          "--yt-spec-background-warning": "color-mix(in srgb, var(--tt-c1) 20%, transparent)",
          "--yt-spec-background-complete": "color-mix(in srgb, var(--tt-c2) 15%, transparent)",
          "--yt-spec-text-complete": "var(--tt-c2)",
          "--yt-spec-overlay-background-heavy": "var(--tt-scrim)",
          "--yt-spec-overlay-background-medium": "color-mix(in srgb, var(--tt-scrim) 60%, transparent)",
          "--yt-spec-overlay-background-medium-light": "color-mix(in srgb, var(--tt-scrim) 30%, transparent)",
          "--yt-spec-overlay-background-light": "color-mix(in srgb, var(--tt-standard) 8%, transparent)",
          "--yt-spec-overlay-background-medium-heavy": "color-mix(in srgb, var(--tt-scrim) 80%, transparent)",
          "--yt-spec-overlay-background-brand": "color-mix(in srgb, var(--tt-c4) 90%, transparent)",
          "--yt-spec-overlay-solid-background": "var(--tt-low)",
          "--yt-spec-overlay-solid-background-inverse": "var(--tt-standard)",
          "--yt-spec-button-chip-background-hover": "color-mix(in srgb, var(--tt-standard) 10%, transparent)",
          "--yt-spec-tonal-background": "color-mix(in srgb, var(--tt-standard) 10%, transparent)",
          "--yt-spec-tonal-background-inverse": "color-mix(in srgb, var(--tt-base) 10%, transparent)",
          "--yt-spec-inverted-background": "var(--tt-inverse-base)",
          "--yt-spec-inverted-background-hover": "color-mix(in srgb, var(--tt-inverse-base) 85%, var(--tt-inverse-standard) 15%)",
          "--yt-spec-scrim-background-gradient-1": "transparent",
          "--yt-spec-scrim-background-gradient-2": "color-mix(in srgb, var(--tt-base) 30%, transparent)",
          "--yt-spec-scrim-background-gradient-3": "color-mix(in srgb, var(--tt-base) 60%, transparent)",
          "--yt-spec-scrim-background-gradient-4": "var(--tt-base)",
          "--yt-spec-snackbar-background": "var(--tt-standard)",
          "--yt-spec-snackbar-text": "var(--tt-base)",
          "--yt-spec-10-percent-layer": "color-mix(in srgb, var(--tt-standard) 10%, transparent)",
          "--yt-spec-15-percent-layer": "color-mix(in srgb, var(--tt-standard) 15%, transparent)",
          "--yt-spec-20-percent-layer": "color-mix(in srgb, var(--tt-standard) 20%, transparent)",
          "--yt-spec-30-percent-layer": "color-mix(in srgb, var(--tt-standard) 30%, transparent)",
          "--yt-spec-40-percent-layer": "color-mix(in srgb, var(--tt-standard) 40%, transparent)",
          "--yt-spec-50-percent-layer": "color-mix(in srgb, var(--tt-standard) 50%, transparent)",
          "--yt-spec-60-percent-layer": "color-mix(in srgb, var(--tt-standard) 60%, transparent)",
          "--yt-spec-70-percent-layer": "color-mix(in srgb, var(--tt-standard) 70%, transparent)",
          "--yt-spec-80-percent-layer": "color-mix(in srgb, var(--tt-standard) 80%, transparent)",
          "--yt-spec-90-percent-layer": "color-mix(in srgb, var(--tt-standard) 90%, transparent)",
          "--yt-spec-suggested-action-background": "var(--tt-high)",
          "--yt-spec-suggested-action-background-hover": "var(--tt-top)",
          "--yt-spec-menu-button-background": "transparent",
          "--yt-spec-badge-chip-background": "var(--tt-high)",
          "--yt-spec-badge-chip-background-hover": "var(--tt-top)",
          "--yt-spec-static-overlay-background-heavy": "var(--tt-scrim)",
          "--yt-spec-static-overlay-background-medium": "color-mix(in srgb, var(--tt-scrim) 60%, transparent)",
          "--yt-spec-static-overlay-background-medium-light": "color-mix(in srgb, var(--tt-scrim) 30%, transparent)",
          "--yt-spec-static-overlay-background-light": "color-mix(in srgb, var(--tt-standard) 8%, transparent)",
          "--yt-spec-static-overlay-background-medium-heavy": "color-mix(in srgb, var(--tt-scrim) 80%, transparent)",
          "--yt-spec-static-brand-red": "var(--tt-error)",
          "--yt-spec-static-overlay-solid-background": "var(--tt-standard)",
          "--yt-searchbox-background": "var(--tt-low)",
          "--yt-searchbox-text-color": "var(--tt-standard)",
          "--yt-searchbox-legacy-border-color": "var(--tt-outline)",
          "--yt-searchbox-legacy-button-color": "var(--tt-standard)",
          "--yt-spec-general-background-a": "var(--tt-base)",
          "--yt-spec-general-background-b": "var(--tt-low)",
          "--yt-spec-general-background-c": "var(--tt-high)",
          "--paper-slider-container-color": "color-mix(in srgb, var(--tt-standard) 15%, transparent)",
          "--paper-slider-container-color-2": "color-mix(in srgb, var(--tt-standard) 30%, transparent)",
          "--paper-slider-knob-color": "var(--tt-standard)",
          "--paper-slider-pin-color": "var(--tt-c4)",
          "--paper-slider-active-color": "var(--tt-c4)",
          "--paper-slider-secondary-color": "color-mix(in srgb, var(--tt-c4) 40%, transparent)",
          "--paper-slider-disabled-active-color": "color-mix(in srgb, var(--tt-standard) 25%, transparent)",
          "--paper-slider-disabled-secondary-color": "color-mix(in srgb, var(--tt-standard) 15%, transparent)",
          "--ytd-menu-popup-header-bg": "var(--tt-low)"
        }
      }
    ]
  }
];
